KERNEL_CFLAGS += CONFIG_HYBRIDSWAP_ZRAM=y
KERNEL_CFLAGS += CONFIG_HYBRIDSWAP=y
KERNEL_CFLAGS += CONFIG_HYBRIDSWAP_SWAPD=y
KERNEL_CFLAGS += CONFIG_HYBRIDSWAP_CORE=y

KBUILD_OPTIONS += CONFIG_HYBRIDSWAP_ZRAM=y
KBUILD_OPTIONS += CONFIG_HYBRIDSWAP=y
KBUILD_OPTIONS += CONFIG_HYBRIDSWAP_SWAPD=y
KBUILD_OPTIONS += CONFIG_HYBRIDSWAP_CORE=y

ifeq ($(VERSION),5)
ifeq ($(PATCHLEVEL),4)
ZRAM_SRC = zram-5.4
EXTRA_CFLAGS += -DCONFIG_ZRAM_5_4
else ifeq ($(PATCHLEVEL),15)
ZRAM_SRC = zram-5.15
EXTRA_CFLAGS += -DCONFIG_ZRAM_5_15
else
ZRAM_SRC = zram-5.10
EXTRA_CFLAGS += -DCONFIG_ZRAM_5_10
endif
else
ZRAM_SRC = zram-6.1
EXTRA_CFLAGS += -DCONFIG_ZRAM_6_1
EXTRA_CFLAGS += -Wframe-larger-than=4096
endif


# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(ANDROID_BUILD_TOP)/motorola/kernel/modules/include

ifneq ($(filter m y,$(CONFIG_HYBRIDSWAP_ZRAM)),)
EXTRA_CFLAGS += -DCONFIG_HYBRIDSWAP_ZRAM
endif

ifneq ($(filter m y,$(CONFIG_HYBRIDSWAP_ZRAM_WRITEBACK)),)
EXTRA_CFLAGS += -DCONFIG_HYBRIDSWAP_ZRAM_WRITEBACK
endif

ifneq ($(filter m y,$(CONFIG_HYBRIDSWAP)),)
EXTRA_CFLAGS += -DCONFIG_HYBRIDSWAP
endif

ifneq ($(filter m y,$(CONFIG_HYBRIDSWAP_SWAPD)),)
EXTRA_CFLAGS += -DCONFIG_HYBRIDSWAP_SWAPD
endif

ifneq ($(filter m y,$(CONFIG_HYBRIDSWAP_CORE)),)
EXTRA_CFLAGS += -DCONFIG_HYBRIDSWAP_CORE
endif

moto_swap-objs += $(ZRAM_SRC)/zram_drv.o
moto_swap-objs += hybridswap/hybridswap_main.o
moto_swap-objs += hybridswap/hybridswap_eswap.o

ifneq ($(filter m y,$(CONFIG_HYBRIDSWAP_ASYNC_COMPRESS)),)
moto_swap-objs += hybridswap/hybridswap_akcompress.o
endif

moto_swap-objs += hybridswap/hybridswap_swapd.o
moto_swap-objs += $(ZRAM_SRC)/zcomp.o

obj-m += moto_swap.o
